// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2S3YVYOw4qkqd8nw4RL-H3lDTgApYWO8',
    appId: '1:747220995902:web:26eeecd27265364298e66f',
    messagingSenderId: '747220995902',
    projectId: 'medireach-53050',
    authDomain: 'medireach-53050.firebaseapp.com',
    storageBucket: 'medireach-53050.firebasestorage.app',
    measurementId: 'G-WP72LSXS62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qN9ROuYVSHVN8rZ-VieIkZJa-4MUNQ8',
    appId: '1:747220995902:android:5375ca9191ad20d398e66f',
    messagingSenderId: '747220995902',
    projectId: 'medireach-53050',
    storageBucket: 'medireach-53050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS3anUyuKYAv_4hWM4Xvk7vJpVqmRSDpE',
    appId: '1:747220995902:ios:7c8ab25cd27ccab398e66f',
    messagingSenderId: '747220995902',
    projectId: 'medireach-53050',
    storageBucket: 'medireach-53050.firebasestorage.app',
    iosBundleId: 'com.example.medireachFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS3anUyuKYAv_4hWM4Xvk7vJpVqmRSDpE',
    appId: '1:747220995902:ios:7c8ab25cd27ccab398e66f',
    messagingSenderId: '747220995902',
    projectId: 'medireach-53050',
    storageBucket: 'medireach-53050.firebasestorage.app',
    iosBundleId: 'com.example.medireachFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2S3YVYOw4qkqd8nw4RL-H3lDTgApYWO8',
    appId: '1:747220995902:web:efbc5e27b3656cca98e66f',
    messagingSenderId: '747220995902',
    projectId: 'medireach-53050',
    authDomain: 'medireach-53050.firebaseapp.com',
    storageBucket: 'medireach-53050.firebasestorage.app',
    measurementId: 'G-JSC099KB5H',
  );
}
